#!/bin/sh
#
mkdir -p /proc /sys /dev /etc /lib

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mdev -s

mkdir -p /mnt/sysroot
mount -t ext4 /dev/mmcblk1p6 /mnt/sysroot
exec switch_root /mnt/sysroot /sbin/init
