#!/bin/sh
#

mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mdev -s

mkdir -p /mnt/sysroot
mount -t ext4 /dev/mmcblk1p7 /mnt/sysroot
if [ $? -eq 0 ]; then
    exec switch_root /mnt/sysroot /sbin/init
fi
