#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

mount -a

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

exec /bin/sh

