#!/bin/sh

runlevel=S
prevlevel=N
umask 022
export runlevel prevlevel

mount -a
mount -t devpts devpts /dev/pts
echo mdev > /proc/sys/kernel/hotplug
mdev -s

#insmod /lib/modules/bcmdhd.ko

mkdir -p var/run
#ifup -a

hostname -F /etc/sysconfig/HOSTNAME
