#!/bin/sh
#
runlevel=S
prevlevel=N
umask 022
export runlevel prevlevel

mount -a
echo mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /var/run

insmod /lib/modules/bcmdhd.ko

ifup -a

hostname -F /etc/sysconfig/HOSTNAME
