#!/bin/sh
#

echo "initramfs working..."
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mdev -s

mkdir -p /mnt/sysroot
mount -t ext4 /dev/mmcblk1p6 /mnt/sysroot

echo "switch to ubuntu rootfs..."
exec switch_root /mnt/sysroot /sbin/init
